[mjw.packages]
mjw-server = "https://github.com/morajlab/mjw-server.git"
mjw-ui = "https://github.com/morajlab/mjw-ui.git"
mjw-documentor = "https://github.com/morajlab/mjw-documentor.git"
mjw-cli = "https://github.com/morajlab/mjw-cli.git"
mjw-lib = "https://github.com/morajlab/mjw-lib.git"
